# -*- coding: utf-8 -*-
"""david.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aA_dOMNHYprgZm5tbDcJwbqwBTP6DpX1

# DAViD Sketch Notebook

This notebook orchestrates the training pipeline. All logic lives in:
- `config.py`: paths, hyperparameters
- `dataset.py`: `OptimizedVideoDataset`, data loaders
- `model.py`: `ClassificationHead`, `SwiGLU`, transforms
- `encoder.py`: ViFi-CLIP feature extractor loader
- `train.py`: training loop, validation, seed setting
- `clip/`: vendored CLIP architecture (for weight compatibility)

## 1. Environment Setup
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pip install ftfy regex decord scikit-learn kagglehub pandas yacs

!sudo apt install aria2

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# from google.colab import userdata
# import kagglehub
# username = userdata.get('OTHER_OTHER_KAGGLE_USERNAME')
# key = userdata.get('OTHER_OTHER_KAGGLE_KEY')
# %env KAGGLE_USERNAME=$username
# %env KAGGLE_KEY=$key

!echo $KAGGLE_USERNAME

import kagglehub

# Download and cache the dataset (returns the local path)
!aria2c -x 16 --http-user=$KAGGLE_USERNAME --http-passwd=$KAGGLE_KEY \
  -o real-vs-gen-videos.zip \
  https://www.kaggle.com/api/v1/datasets/download/farhanwew/real-vs-gen-videos

!unzip /content/real-vs-gen-videos.zip -d /content/dataset

!rm /content/real-vs-gen-videos.zip

import kagglehub

# Download and cache the dataset (returns the local path)
!aria2c -x 16 --http-user=$KAGGLE_USERNAME --http-passwd=$KAGGLE_KEY \
  -o dfk3-set.zip \
  https://www.kaggle.com/api/v1/datasets/download/faizkautsar/data-dfk3-aitf

!unzip /content/dfk3-set.zip -d /content/dfk3

"""## 2. Load Feature Extractor"""

!git clone https://github.com/aitf-its-tim3-dfk/david

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/david

!git checkout feat-cddb

from config import CLIP_ARCH, CLASS_NAMES
from encoder import load_feature_extractor

feature_extractor = load_feature_extractor(
    arch=CLIP_ARCH,
    class_names=CLASS_NAMES,
    checkpoint_path="/content/drive/MyDrive/k400_clip_complete_finetuned_30_epochs.pth",
).cuda()

"""## 3. Prepare Data"""

import os
from config import DATASET_ROOT, METADATA_CSV, BATCH_SIZE, VAL_SPLIT, NUM_WORKERS
from model import build_train_transform, build_transform
from dataset import get_combined_loaders

train_transform = build_train_transform(224)
val_transform = build_transform(224)

train_loader, val_loader = get_combined_loaders(
    train_transform=train_transform,
    val_transform=val_transform,
    video_dataset_root="/content/dataset",
    video_metadata_csv="/content/dataset/metadata_clean_v2.csv",
    cddb_root="/content/dfk3/CDDB",
    val_split=VAL_SPLIT,
    batch_size=64,
    num_workers=22,
)

"""## 4. Train"""

from config import LEARNING_RATE, NUM_EPOCHS, INPUT_DIM, NUM_CLASSES, CLASS_NAMES, BEST_MODEL_SAVE_PATH
from train import set_seed, run_training

set_seed(42)

classifier = run_training(
    feature_extractor=feature_extractor,
    train_loader=train_loader,
    val_loader=val_loader,
    input_dim=INPUT_DIM,
    num_classes=3,
    class_names=("real", "deepfake", "ai_gen"),
    lr=LEARNING_RATE,
    num_epochs=2,
    save_path=BEST_MODEL_SAVE_PATH,
)

"""## 5. Save & Cleanup"""

import shutil
from datetime import datetime

model_name = f"best_detector_model_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pt"
shutil.copy(BEST_MODEL_SAVE_PATH, model_name)
shutil.copy(model_name, '/content/drive/MyDrive/')
print(f'Saved {model_name} to Drive')

from google.colab import drive, runtime

drive.flush_and_unmount()
runtime.unassign()

